/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
  safelist: [
    'container',
    'mx-auto',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'md:grid-cols-1',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'lg:grid-cols-1',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'w-full',
    'h-full',
    'flex',
    'flex-col',
    'justify-between',
    'justify-evenly',
    'justify-start',
    'justify-end',
    'justify-center',
    'items-center',
    'items-start',
    'items-end',
    'items-stretch',
    'max-w-7xl',
    'h-screen',
    'lg:min-h-[80vh]',
    'h-auto',
    'lg:max-w-5xl',
    'w-auto',
    'gap-4',
  ],
};
